let productsDB = [
    {
        id:1,
        imgUrl:"img/product/product-1.jpg",
        title: "Sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:2,
        imgUrl:"img/product/product-2.jpg",
        title: "Sporty W Nolty",
        price: 49.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:3,
        imgUrl:"img/product/product-3.jpg",
        title: "Sporty",
        price: 49.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:4,
        imgUrl:"img/product/product-4.jpg",
        title: "Sporty",
        price: 49.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:5,
        imgUrl:"img/product/product-5.jpg",
        title: "Flowy striped Shirt",
        price: 99.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:6,
        imgUrl:"img/product/product-6.jpg",
        title: "Flowy striped Shirt",
        price: 89.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:7,
        imgUrl:"img/product/product-7.jpg",
        title: "jeans",
        price: 29.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:8,
        imgUrl:"img/product/product-8.jpg",
        title: "Wide Leg Bardot",
        price: 65.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:9,
        imgUrl:"img/product/product-9.jpg",
        title: "Fit Micro Corduroy Shirt",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:10,
        imgUrl:"img/product/product-10.jpg",
        title: "Blazer Coat Business Suit",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:11,
        imgUrl:"img/product/product-11.jpg",
        title: "Blazer Coat Business Suit",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:12,
        imgUrl:"img/product/product-12.jpg",
        title: "Skine Jeans",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
]

localStorage.setItem('products', JSON.stringify(productsDB));