let productsDB = [
    {
        id:1,
        imgUrl:"img/product/product-1.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:2,
        imgUrl:"img/product/product-2.jpg",
        title: "adel",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:3,
        imgUrl:"img/product/product-3.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:4,
        imgUrl:"img/product/product-4.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:5,
        imgUrl:"img/product/product-5.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:6,
        imgUrl:"img/product/product-6.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:7,
        imgUrl:"img/product/product-7.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:8,
        imgUrl:"img/product/product-8.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:9,
        imgUrl:"img/product/product-9.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:10,
        imgUrl:"img/product/product-10.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:11,
        imgUrl:"img/product/product-11.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
    {
        id:12,
        imgUrl:"img/product/product-12.jpg",
        title: "sporty",
        price: 59.0,
        starImgUrl:"img/5stars.jpg",
        qty: 1,
    },
]

localStorage.setItem('products', JSON.stringify(productsDB));